### PR TITLE
[vscode] Configure jar file and server home folder through settings

### PR DESCRIPTION
**Pull request by tdroxler**
I gave a try to configure the jar file location as well as the home folder for logs through the vscode settings. When the user open for the first time the extension, an error message is displayed with a button to redirect to the settings.

image

When clicking:
 
image

Here are all current settings:

image

@simerplaha WDYT of this approach? It's always very bias as it's an approach I like, as you can be explicit on which server jar to run.

The ultimate version would be to let the extension download the jar file, but that implies more work on the extension side while it's more important to work on the server side, we could also let someone from the community do that.

### CODE REVIEW

**Comment by simerplaha** [comment]
Hi Thomas, I've got a few questions, I can write them out if you'd like to discuss them?

In short, any chance you would consider removing the `ralph-lsp.jar` config setting and have the JAR published with the plugin and let the editor do the heavy lifting for us, like versioning and plugin update notifications? That would keep things simple and not add manual work for the user.

**Comment by tdroxler** [comment]
Hi Simer,

I'm totally open to go with the way you propose, anyway I won't be the once using the vscode extension :sweat_smile: 

I see it as two paradigm, that are usually confronting:

* One click install team
* I'm a super-user-better-than-others team #GNUForever :stuck_out_tongue_closed_eyes: 

joke aside, it hides some truth that some devs prefer one click install stuff and others prefers to have more control.
I don't have statistics, but I can imagine most devs likes to goes with option 1 (unfortunately^^).

The things that I don't like with that approach, especially in the LSP world is that we broke the concept of a protocol, where you have the client on one side and a sever on the other. Here we are blending everything in one big app. If we add `ralph-lsp.jar` to the vs-code extension, as well as the nvim/intellij/emacs/nano ones. We end up with 5 times the `ralph-lsp.jar` file on our computer. It binds to much the server with the client. 
If there is a new server version, devs will need to download the new client version!?! 

In my ideal world, a client should be able to use whatever server and a server should be usable by any client. That's why I prefer to have one jar in one place on my computer and tell each client how to start the server. If I want to update my server or even use another one, I just update my server, don't need to touch the client. Thinking out loud, but `ralph-lsp` should not even be a jar, but just an executable, so in the client you can just tell which programs to launch and this programs has to be in the `$PATH`

But I realize most of the times that this approach is shared by less people than others, so I won't fight to much for it.

Maybe one last point, IMO it's not even us who should take care of clients/extensions, we should only provide the server, the plugins should maybe even have there own repo (again only my opinion). Thus I don't think we should spent to much time on them, the solution in this PR is a quick way to have an extension working without too much work, because implementing a downloading/versioning/notification etc is a whole job by itself, while adding completion/jump-to-definition etc to our sever seems more important to me.

Sorry this was not a short answer :sweat_smile:

**Comment by simerplaha** [comment]
I'm not sure how to respond. I don't have strong opinions on the protocol. The goal was to keep the plugins easy to use. Feel free to merge if you think this is the right approach. Maybe the easy of use with "One click install" is not the way to go and "I'm a super-user-better-than-others" would create better development experience.

I will document the issues I see:

- Since downloading `ralph-lsp.jar` is a manual process, the user is required to watch this repository for new releases and downloading the JAR manually, rather than getting push notifications in their editor to install latest plugin releases, which is how other language plugins I currently use behave. For folks wanting to use nightly builds, this will become laborious.

- This screenshot asks the user to `.. Don't forget to reload after editing ...`, requiring the user to do "work" for validation. If this was deferred to the editor, the reload would happen automatically without any manual validation. In case of an error input, the user will be required to do multiple restarts to validate the input.
  image

- > but  that implies more work on the extension side while it's more important to work on the server side, we could also let someone from the community do that.  

  This comments suggests that eventually more code will be required on the client side to better manage the JAR for the user. The initial goal for the client side code was to keep it bare minimum template code. Considering different IDEs require plugins written in different languages, this will add additional workload in multiple languages.

**Comment by tdroxler** [comment]
I fully agree on the 2 first issues you described, the solution on this PR will give more work and errors on user side, which leads to point 3: If we want to solve the 2 first issues, we need to spend a good amount of time on the extension. 

The question is: Do we want to send more time on it rather than the server itself? IMO no, but we can discuss this.

The proposal in this PR isn't ideal and I can't say it's the right approach or not, but it allows to quickly gives devs a usable VSIX to  download.

**Comment by simerplaha** [comment]
> If we want to solve the 2 first issues, we need to spend a good amount of time on the extension.

Not really. Publishing the JAR with the plugin as suggested [here](https://github.com/alephium/ralph-lsp/pull/91#issuecomment-1916016473) and implemented [here](https://github.com/alephium/ralph-lsp/pull/90), will make the first two issues disappear and the third will no longer be required.

If you'd like to inherit the above issues, feel free to merge or please consider getting a third opinion.

**Comment by tdroxler** [comment]
Ok so let's go with https://github.com/alephium/ralph-lsp/pull/90, but I have one request: to keep [that line](https://github.com/alephium/ralph-lsp/pull/90/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91L35), the jar file could be copied/moved when building the extension, maybe when [executing the package.json script](https://github.com/alephium/ralph-lsp/blob/vsix/plugin-vscode/package.json#L51).

As a non-vscode dev, if I was a new user I would find very weird that the server-jar is located inside the vscode plugin and I would ask where's the vim's server jar

**Pull request closed without merging**
