### PR TITLE
Scalafmt

### LINKED ISSUE #24: Introduce `scalafmt`
As we are now 2 working on the project, it could be useful to force having the same syntax. 

WDYT?

### PR DESCRIPTION
**Pull request by simerplaha**
Resolves #24. Left a few files unformatted.

### CODE REVIEW

**Review by tdroxler — APPROVED** [review]
:+1: thx a lot

**Review by tdroxler — APPROVED** [review]

**Comment by simerplaha** [comment]
The conflicts in formatting is from the previous PR. Would you like to format them, including others that I've left out and haven't formatted? (not authored by me).

**Comment by tdroxler** [comment]
> The conflicts in formatting are from the previous PR. Would you like to format them, including others that I've left out and haven't formatted? (not authored by me).

no no you can format on your side, no problem for me

**Comment by simerplaha** [comment]
`scalaFmtCheck` is failing on [Windows](https://github.com/alephium/ralph-lsp/actions/runs/8641853694/job/23692262695#step:4:24). I'm going to remove the `scalaFmtCheck` from `scala.yml`. A Windows task for some other day.

**Comment by tdroxler** [comment]
> `scalaFmtCheck` is failing on [Windows](https://github.com/alephium/ralph-lsp/actions/runs/8641853694/job/23692262695#step:4:24) but passes on [MacOS and Ubuntu](https://github.com/alephium/ralph-lsp/actions/runs/8641955439). I'm going to remove the `scalaFmtCheck` from `scala.yml`. A Windows task for some other day.

grrrr Windows!!!!

**Pull request merged**
