### PR TITLE
Optional compiler options

### LINKED ISSUE #271: Optional `compilerOptions`
Latest version of `ralphc` introduced a new compiler option: `"ignoreUnusedFunctionReturnWarnings": false`. If we release from master now, existing projects will get the error `missing keys in dictionary: ignoreUnusedFunctionReturnWarnings`. 

Should we make `compilerOptions` optional before releasing, so that the above error does not occur?

Default `compilerOptions` being [`CompilerOptions.Default`](https://github.com/alephium/alephium/blob/b78170a4bd2cc648c84a747623cbe1cc37250dba/ralph/src/main/scala/org/alephium/ralph/CompilerOptions.scala#L30).

@tdroxler

### LINKED ISSUE #280: `alephium.config.ts` build overwrites all configured `ralph.json` values when a configuration is missing
# Issue 

The `alephium.config.ts` build overwrites **ALL** configured values when one of the configs is missing. 

# Reproduce

1. Update `ralph.json` to following, where the `ignoreUnusedFunctionReturnWarnings` config is missing:

    ```json
    {
      "compilerOptions": {
        "ignoreUnusedConstantsWarnings": true,
        "ignoreUnusedVariablesWarnings": true,
        "ignoreUnusedFieldsWarnings": true,
        "ignoreUnusedPrivateFunctionsWarnings": true,
        "ignoreUpdateFieldsCheckWarnings": true,
        "ignoreCheckExternalCallerWarnings": true
      },
      "contractPath": "my_code"
    }
    ```

2. Create, edit or save `alephium.config.ts` the following configurations, so `TSBuild` process gets triggered:
     
     ```ts
    compilerOptions: {
      ignoreUnusedConstantsWarnings: false
    },

      ```
    
    
      - **Expected behaviour:** The existing configurations in `ralph.json` should remain unchanged, and only the missing 
         `ignoreUnusedFunctionReturnWarnings` should be added with a default value, along with other updated configs in `alephium.config.ts`. 
      - **Actual behaviour**: 
        - All existing configurations are overwritten to `false`.
        - It also overwrites `contractPath` from `"my_code"` to `"contracts"`.
    
    ```json
    {
      "compilerOptions": {
        "ignoreUnusedConstantsWarnings": false,
        "ignoreUnusedVariablesWarnings": false,
        "ignoreUnusedFieldsWarnings": false,
        "ignoreUnusedPrivateFunctionsWarnings": false,
        "ignoreUpdateFieldsCheckWarnings": false,
        "ignoreCheckExternalCallerWarnings": false,
        "ignoreUnusedFunctionReturnWarnings": false
      },
      "contractPath": "contracts"
    }
    ```

# Cause

This occurs because the JSON parser in the build process requires all configurations to be present in order to create the config object `RalphcConfigState.Parsed`, which becomes unavailable to `TSBuild`.

# Solution 

PR #272 resolves this.

### PR DESCRIPTION
**Pull request by simerplaha**
- Resolves #271.
- Resolves #280.

### CODE REVIEW

**Comment by simerplaha** [comment]
Just remembered, when #239 is implemented, the changes in this PR won't be necessary.

Just noting that this PR is blocking the release. We are currently on Node version 3.4.0, which is a month old, and there have been four releases of Node since then.

**Comment by simerplaha** [comment]
Hey @tdroxler, now that `TSBuild` is merged, the error `missing keys in dictionary: ignoreUnusedFunctionReturnWarnings` from issue #271 would **ONLY** occur for existing projects that don't contain the `alephium.config.ts` file. Are we ok with this? We don't want `compilerOptions` to be optional anymore? If yes, this PR can be closed before releasing.

**Comment by simerplaha** [comment]
@tdroxler, this PR also resolves issue #280.

**Review by tdroxler — APPROVED** [review]
I think it's good to have `compilerOptions` optional anyway, if someone bootstrap a ralph project and hasn't yet some `alephium.config.ts` it's good if he doesn't need to care about `ralph.json`

LGTM

**Pull request merged**
